/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetMessage */

#ifndef _Included_GetMessage
#define _Included_GetMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetMessage
 * Method:    getMessage
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GetMessage_getMessage
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
